name: Test

on:
  pull_request:
  push:
    branches:
      - primary

jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run ci
  integrationTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build
      - uses: ./
        id: result
        with:
          format: '[tada]'
      - run: exit 1
        name: "Fail unless steps.result.outputs.date == 'tada'"
        if: steps.result.outputs.date != 'tada'
